#!/usr/bin/env python3

#hkpac - Gestor de paquetes para el repositorio Hacking-Utils.
#Escrito por Darth Venom y Tobi Emotic.
#< = >

import sys;
import os;
import json;

# Definición de la función main(). En Python esta función no es necesaria.

def main():
#    pcd = os.getcwd()          //descartar
#    pcd = '/usr/local/bin'
    F=None
    if os.system('uname -a | grep Android &> /dev/null') == 0:
        termux=True
    else:
        termux=False
    if not termux:
        os.chdir('/etc')
    else:
        try:
            os.chdir('/data/data/com.termux/files/home/.config/')
        except FileNotFoundError:
            os.chdir('/data/data/com.termux/files/home')
            os.mkdir('.config')
            os.chdir('.config')
        try:
            os.chdir('hkpac')
        except FileNotFoundError:
            os.mkdir('hkpac')
            os.chdir('hkpac')

    if len(sys.argv) == 1:
        print("{}error:{} No se ha especificado una operacion".format(red,nml))
        exit(1)
        ###################################Chequeo de configuración#################################

    if 'hkpac.conf' in os.listdir():
        con=open('hkpac.conf','r')
        conf=json.load(con)
        del(con)
        instdir=conf['conf'][0]['instdir']
#        termux=conf['conf'][0]['Termux']               //Ajuste descartado
    else:
        if os.system('uname -a | grep Android &> /dev/null') == 0:
            termux=True
            instdir='/data/data/com.termux/files/usr/bin'

        else:
            termux=False
            instdir='/usr/local/bin'
        conf={'conf':[{'instdir': instdir}]}

    x=1
    op="null"
    for i in sys.argv:

        ############################################################################################
        #######################################Selección de operación###############################

        if op == "null":

            if sys.argv[x] == "install":
                op="install"
                x+=1
                continue
            elif sys.argv[x] == "update":
                op="update"
                x+=1
                continue
            elif sys.argv[x] == "search":
                op="search"
                x+=1
                continue
            elif sys.argv[x] == "remove":
                op="remove"
                x+=1
                continue
            elif sys.argv[x] == "removeconf":
                op="rmconf"
                x+=1
                continue
            elif sys.argv[x] == "rmwconf":
                op="rmwconf"
                x+=1
                continue
            elif sys.argv[x] == "config":
                op="config"
                x+=1
                continue
            else:
                print("hkpac: Opción invalida - " + sys.argv[x])
                exit(1)

        #############################################################################################
        ######################################Operación install######################################

        elif op == "install":

            if len(sys.argv)-1 < x:
                print('{}error:{} No se ha especificado un objetivo.'.format(red,nml))
                exit(1)
            if len(sys.argv[x]) == 0:
                print('{}error:{} No se ha especificado un objetivo.'.format(red,nml))
                exit(1)
            if F == None:
                if not 'hkpac.json' in os.listdir():
                    print('Faltan los datos de hkpac. Ejecute \'hkpac update\'')
                    exit(1)
                with open('hkpac.json') as F:
                    hkpac = json.load(F)
            if sys.argv[x] in hkpac['packs'][0]:
                os.chdir(instdir)
                print("Obteniendo archivo...")
                os.system('wget https://raw.githubusercontent.com/VENOM-InstantDeath/hkprogs/master/' + hkpac['packs'][0][sys.argv[x]]['local'] + sys.argv[x] + " &> /dev/null")
                os.system('chmod +x ' + sys.argv[x])
                print("Modificado como ejecutable.")
                if not termux:
                    os.chdir('/etc')
                else:
                    os.chdir('/data/data/com.termux/files/home/.config/hkpac')
                if x+1 > len(sys.argv)-1:
                    exit()
                else:
                    x+=1
                    continue
            else:
                print('{}error:{} Objetivo no encontrado: '.format(red,nml) + sys.argv[x])
                exit(1)
        
        ##############################################################################################
        ######################################Operación search########################################

        elif op == "search":

            if len(sys.argv)-1 < x:
                print('{}error:{} No se ha especificado un objetivo.'.format(red,nml))
                exit(1)
            if len(sys.argv[x]) == 0:
                print('{}error:{} No se ha especificado un objetivo.'.format(red,nml))
                exit(1)
            if F == None:
                if not 'hkpac.json' in os.listdir():
                    print('Faltan los datos de hkpac. Ejecute \'hkpac update\'')
                    exit(1)
                with open('hkpac.json') as F:
                    hkpac = json.load(F)
            if sys.argv[x] in hkpac['packs'][0]:
                print("{} encontrado en {}".format(sys.argv[x],hkpac['packs'][0][sys.argv[x]]['local']))
                if not termux:
                    os.chdir('/etc')
                else:
                    os.chdir('/data/data/com.termux/files/home/.config/hkpac')
                if x+1 > len(sys.argv)-1:
                    exit()
                else:
                    x+=1
                    continue
            else:
                print('Objetivo no encontrado: ' + sys.argv[x])
                exit(1)

        ##############################################################################################
        ######################################Operación config########################################

        elif op == "config":
            
            if len(sys.argv)-1 < x:
                print('{}error:{} No se ha especificado un ajuste.'.format(red,nml))
                exit(1)
            if len(sys.argv[x]) == 0:
                print('{}error:{} No se ha especificado un ajuste.'.format(red,nml))
                exit(1)

            EUID=os.popen("echo $EUID").read().strip()
            if len(EUID) == 0:
                EUID=False
            elif not len(EUID) == 0 and int(EUID) == 0:
                EUID=True
            else:
                EUID=False

            if sys.argv[x] == 'list':
                for i in conf['conf'][0]:
                    print(i)
                exit()

            if sys.argv[x] == 'instdir':
                x+=1

                if len(sys.argv)-1 < x:
                    print('{}error:{} No se ha especificado el valor.'.format(red,nml))
                    exit(1)
                if len(sys.argv[x]) == 0:
                    print('{}error:{} No se ha especificado el valor.'.format(red,nml))
                    exit(1)

                if sys.argv[x] == 'show':
                    print(instdir)
                    exit()
                if sys.argv[x] == 'default':

                    if EUID == False and not termux:
                        print('{}error:{} Permisos insuficientes. Intenta ejecutando como root.'.format(red,nml))
                        exit(1)

                    if not termux:
                        os.chdir('/etc')
                    else:
                        os.chdir('/data/data/com.termux/files/home/.config/hkpac')
                    if not 'hkpac.conf' in os.listdir():
                        F=open('hkpac.conf','w+')
                    else:
                        F=open('hkpac.conf','w')
                    conf['conf'][0]["instdir"] = '/usr/local/bin'
                    F.write(json.dumps(conf,indent=4))
                    F.seek(0)
                    F.close()
                    print('Instdir cambiado a ' + '/usr/local/bin')
                    exit()

                if EUID == False and not termux:
                    print('{}error:{} Permisos insuficientes. Intenta ejecutando como root.'.format(red,nml))
                    exit(1)

                try:
                    os.chdir(sys.argv[x])
                except FileNotFoundError:
                    print('{}error:{} El directorio especificado no existe.'.format(red,nml))
                    exit(1)
                if not termux:
                    os.chdir('/etc')
                else:
                    os.chdir('/data/data/com.termux/files/home/.config/hkpac')
                if not 'hkpac.conf' in os.listdir():
                    F=open('hkpac.conf','w+')
                else:
                    F=open('hkpac.conf','w')
                conf['conf'][0]["instdir"] = sys.argv[x]
                F.write(json.dumps(conf,indent=4))
                F.seek(0)
                F.close()
                print('Instdir cambiado a ' + sys.argv[x])
                exit()
            else:
                print('{}error:{} El ajuste especificado no existe.'.format(red,nml))
                exit(1)

        ##############################################################################################
        ###################################Operación remove###########################################

        elif op == "remove":

            if len(sys.argv)-1 < x:
                print('{}error:{} No se ha especificado un objetivo.'.format(red,nml))
                exit(1)
            if len(sys.argv[x]) == 0:
                print('{}error:{} No se ha especificado un objetivo.'.format(red,nml))
                exit(1)
            if F == None:
                if not 'hkpac.json' in os.listdir():
                    print('Faltan los datos de hkpac. Ejecute \'hkpac update\'')
                    exit(1)
                with open('hkpac.json') as F:
                    hkpac = json.load(F)
            if sys.argv[x] in hkpac['packs'][0]:
                os.chdir(instdir)
                if sys.argv[x] in os.listdir():
                    os.remove(sys.argv[x])
                    print(sys.argv[x] + ' se ha removido.')
                else:
                    print(sys.argv[x] + ' no está instalado.')
                if x+1 > len(sys.argv)-1:
                    exit()
                else:
                    x+=1
                    continue
            else:
                print('{}error:{} Objetivo no encontrado: '.format(red,nml) + sys.argv[x])
                exit(1)

        ##############################################################################################
        ######################################Operacion update########################################

        elif op == "update":
            if not termux:
                os.chdir('/etc')
            else:
                os.chdir('/data/data/com.termux/files/home/.config/hkpac')

            EUID=os.popen("echo $EUID").read().strip()
            if len(EUID) == 0:
                EUID=False
            elif not len(EUID) == 0 and int(EUID) == 0:
                EUID=True
            else:
                EUID=False
            if EUID == False and not termux:
                print('{}error:{} Permisos insuficientes. Intenta ejecutando como root.'.format(red,nml))
                exit(1)
            if not 'hkpac.json' in os.listdir():
                os.system('wget https://raw.githubusercontent.com/VENOM-InstantDeath/hkprogs/master/extra/hkpac.json &> /dev/null')
            else:
                os.remove('hkpac.json')
                os.system('wget https://raw.githubusercontent.com/VENOM-InstantDeath/hkprogs/master/extra/hkpac.json &> /dev/null')
            print("Datos actualizados correctamente.")
            exit()






# if que comprueba si el ejecutor del programa es el programa en sí o si está siendo ejecutado como módulo o desde otro programa. Si el código está siendo ejecutado por el propio programa, entonces se ejecuta el interior del if (ingresando a la función main()).

if __name__ == '__main__':

    #variables con escapes ANSI
    red="\033[1;31m";
    green="\033[1;32m";
    yellow="\033[1;33m";
    blue="\033[1;34m";
    purple="\033[1;35m";
    light="\033[1;36m";
    white="\033[1;37m";
    nml="\033[0m";

    #llamada a la función main()
    main();
